name: CI

on:
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Action Lint
        uses: Adzz/yarn_command_action@v1.0.0
        with:
          command: lint
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Application Build
        uses: Adzz/yarn_command_action@v1.0.0
        with:
          command: build

