name: Build

on:
  push:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Action Lint
        uses: borales/actions-yarn@v2.0.0
        with:
          command: lint
  build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Install dependency
        uses: borales/actions-yarn@v2.0.0
        with:
          cmd: install
      - name: Application Build
        uses: borales/actions-yarn@v2.0.0
        with:
          command: build

